version: '2'
services:

  www:
    build: www/.
    volumes:
      - ./www/app:/opt/www/app
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    volumes:
      - ./db/database:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: supersecure
